# Install latest node version
FROM node:latest

# Pass the work directory program for blue code
WORKDIR /blue

# Copy the package.json to app directory
COPY package.json /blue

# Install  node package manager
RUN npm install

# Copy all files
COPY . /blue

# Script pass
CMD ["npm", "start"]
